language: python
python:
  - 3.6
services:
  - docker
sudo: required
install:
  - pip install -r requirements-doc.txt
script:
  - docker run -v $(pwd):/root/apt-repo python:3.6 pip install /root/apt-repo && python -c "import apt_repo"
  - cd doc
  - pydocmd build
  - cd ..
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: doc/_build/site
 on:
   branch: master
